extends Node
class_name GameConfig

## Global defaults
const GLOBAL_STARTING_MONEY: float = 100.0
const GLOBAL_STARTING_RAW_COFFEE: int = 0
const GLOBAL_MAX_COFFEE_CAPACITY: int = 10
const GLOBAL_STARTING_SATISFACTION: float = 50.0

## Cats home tuning
const CAT_HOME_SPAWN_INTERVAL: float = 30.0
const CAT_HOME_MIN_SPAWN_CHANCE: float = 0.1
const CAT_HOME_MAX_SPAWN_CHANCE: float = 0.5
const CAT_HOME_BASE_MAX_CATS: int = 3
const CAT_HOME_SPAWN_RADIUS: float = 30.0
const CAT_HOME_MAX_CATS_PER_LEVEL: int = 2

## Storage tuning
const STORAGE_STARTING_INVENTORY: int = 20
const STORAGE_BASE_MAX_INVENTORY: int = 40
const STORAGE_ARRIVAL_INTERVAL: float = 60.0
const STORAGE_BASE_ARRIVAL_AMOUNT: int = 5
const STORAGE_AUTO_FILL_COST_PER_UNIT: float = 3.0
const STORAGE_MAX_INVENTORY_PER_LEVEL: int = 10
const STORAGE_ARRIVAL_AMOUNT_PER_LEVEL: int = 5

## Coffee machine tuning
const MACHINE_BREWING_TIME: float = 10.0
const MACHINE_STARTING_STOCK: int = 5
const MACHINE_BASE_MAX_STOCK: int = 10
const MACHINE_FAIL_CHANCE: float = 0.33
const MACHINE_BAD_TASTE_CHANCE: float = 0.33
const MACHINE_TAKE_MONEY_ON_FAIL_CHANCE: float = 0.5
const MACHINE_COFFEE_PRICE: float = 10.0
const MACHINE_SATISFACTION_REWARD: float = 5.0
const MACHINE_SATISFACTION_PENALTY: float = -5.0
const MACHINE_STOCK_MULTIPLIER_PER_LEVEL: int = 1
const MACHINE_BREWING_TIME_DECREASE_PER_LEVEL: float = 0.2
const MACHINE_BREWING_TIME_MIN: float = 1.0
const MACHINE_FAIL_CHANCE_DECREASE_PER_LEVEL: float = 0.05
const MACHINE_BAD_TASTE_CHANCE_DECREASE_PER_LEVEL: float = 0.05
const MACHINE_SATISFACTION_REWARD_PER_LEVEL: float = 0.5
const MACHINE_SATISFACTION_PENALTY_PER_LEVEL: float = 0.5
const MACHINE_SATISFACTION_PENALTY_MAX: float = -1.0

## Cat tuning
const CAT_MAX_HEALTH: int = 10
const CAT_MAX_ENERGY: float = 100.0
const CAT_ENERGY_DRAIN_PER_SEC: float = 1.0
const CAT_WANDER_RADIUS: float = 300.0
const CAT_STOP_DISTANCE: float = 20.0
const CAT_MOVE_SPEED: float = 50.0
const CAT_RESCORE_INTERVAL: float = 1.0
const CAT_SWITCH_WAIT_THRESHOLD: float = 3.0
const CAT_SWITCH_SCORE_MARGIN: float = 10.0
const CAT_MACHINE_SCORE_BASE: float = 100.0
const CAT_MACHINE_SCORE_UPGRADE_BONUS: float = 5.0
const CAT_MACHINE_SCORE_DISTANCE_WEIGHT: float = 1.0
const CAT_MACHINE_SCORE_QUEUE_WEIGHT: float = 5.0
const CAT_MACHINE_SCORE_BUSY_PENALTY: float = 5.0
const CAT_MACHINE_OUT_OF_STOCK_SCORE: float = -10000.0
const CAT_DEFAULT_SATISFACTION_BOOST: float = 5.0
const CAT_COFFEE_FAIL_PENALTY: float = -10.0

## Player tuning
const PLAYER_MOVE_SPEED: float = 200.0

## Phone UI economy tuning
const RAW_BUY_AMOUNT: int = 10
const RAW_BUY_COST: float = 40.0
const BUILD_COST_MACHINE: float = 200.0
const BUILD_COST_STORAGE: float = 500.0
const BUILD_COST_CAT_HOME: float = 150.0
const UPGRADE_MACHINE_BASE_COST: float = 40.0
const UPGRADE_MACHINE_PER_LEVEL_COST: float = 25.0
const UPGRADE_STORAGE_BASE_COST: float = 30.0
const UPGRADE_STORAGE_PER_LEVEL_COST: float = 20.0
const UPGRADE_CAT_HOME_BASE_COST: float = 35.0
const UPGRADE_CAT_HOME_PER_LEVEL_COST: float = 25.0
const STORAGE_TRANSFER_AMOUNT: int = 10
